//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS_Projekat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMS_Projekat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do:.
        /// </summary>
        internal static string _do {
            get {
                return ResourceManager.GetString("do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analgetik.
        /// </summary>
        internal static string analgetik {
            get {
                return ResourceManager.GetString("analgetik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankete.
        /// </summary>
        internal static string Ankete {
            get {
                return ResourceManager.GetString("Ankete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antibiotik.
        /// </summary>
        internal static string antibiotik {
            get {
                return ResourceManager.GetString("antibiotik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antipetik.
        /// </summary>
        internal static string antipetik {
            get {
                return ResourceManager.GetString("antipetik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antiseptik.
        /// </summary>
        internal static string antiseptik {
            get {
                return ResourceManager.GetString("antiseptik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broj.
        /// </summary>
        internal static string brojM {
            get {
                return ResourceManager.GetString("brojM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prostorije:.
        /// </summary>
        internal static string BrojProstorije {
            get {
                return ResourceManager.GetString("BrojProstorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj sprata:.
        /// </summary>
        internal static string BrojSprata {
            get {
                return ResourceManager.GetString("BrojSprata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brzina prijema na pregled?.
        /// </summary>
        internal static string BrzinaPrijema {
            get {
                return ResourceManager.GetString("BrzinaPrijema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obično.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li biste preporučili bolnicu?.
        /// </summary>
        internal static string DaLiBolPreporuciti {
            get {
                return ResourceManager.GetString("DaLiBolPreporuciti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li biste preporučili doktora?.
        /// </summary>
        internal static string DaLiDrPreporuciti {
            get {
                return ResourceManager.GetString("DaLiDrPreporuciti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li Vas je doktor pažiljivo slušao?.
        /// </summary>
        internal static string DaLiSlusa {
            get {
                return ResourceManager.GetString("DaLiSlusa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datum kreiranja ankete.
        /// </summary>
        internal static string dateOfPoll {
            get {
                return ResourceManager.GetString("dateOfPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datum.
        /// </summary>
        internal static string datumM {
            get {
                return ResourceManager.GetString("datumM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja: 03.05.1959..
        /// </summary>
        internal static string datumRodjenja {
            get {
                return ResourceManager.GetString("datumRodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dinamička.
        /// </summary>
        internal static string dinamicka {
            get {
                return ResourceManager.GetString("dinamicka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocena za doktor.
        /// </summary>
        internal static string doctorRatingPoll {
            get {
                return ResourceManager.GetString("doctorRatingPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dodaj lek.
        /// </summary>
        internal static string DodajLek {
            get {
                return ResourceManager.GetString("DodajLek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj opremu.
        /// </summary>
        internal static string DodajOpremu {
            get {
                return ResourceManager.GetString("DodajOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj prostoriju.
        /// </summary>
        internal static string DodajProstoriju {
            get {
                return ResourceManager.GetString("DodajProstoriju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sastojke.
        /// </summary>
        internal static string DodajSastojke {
            get {
                return ResourceManager.GetString("DodajSastojke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zamene.
        /// </summary>
        internal static string DodajZamene {
            get {
                return ResourceManager.GetString("DodajZamene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zamenski lek.
        /// </summary>
        internal static string DodajZamenskiLek {
            get {
                return ResourceManager.GetString("DodajZamenskiLek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupna količina:.
        /// </summary>
        internal static string DostupnaKolicina {
            get {
                return ResourceManager.GetString("DostupnaKolicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to komentar doktora.
        /// </summary>
        internal static string drCom {
            get {
                return ResourceManager.GetString("drCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string Engleski {
            get {
                return ResourceManager.GetString("Engleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za pregled.
        /// </summary>
        internal static string examRoom {
            get {
                return ResourceManager.GetString("examRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocena za bolnicu.
        /// </summary>
        internal static string hospitalRatingPoll {
            get {
                return ResourceManager.GetString("hospitalRatingPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ime.
        /// </summary>
        internal static string imeM {
            get {
                return ResourceManager.GetString("imeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventar.
        /// </summary>
        internal static string Inventar {
            get {
                return ResourceManager.GetString("Inventar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventar prostorije.
        /// </summary>
        internal static string InventarProstorije {
            get {
                return ResourceManager.GetString("InventarProstorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite prostoriju u koju želite da premestite opremu: .
        /// </summary>
        internal static string IzaberiProstorijuUKoju {
            get {
                return ResourceManager.GetString("IzaberiProstorijuUKoju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite lek koji želite da dodate:.
        /// </summary>
        internal static string IzaberiteLekKojiZeliteDaDodat {
            get {
                return ResourceManager.GetString("IzaberiteLekKojiZeliteDaDodat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izabrani doktor pacijenta:.
        /// </summary>
        internal static string IzabraniDoktorPacijenta {
            get {
                return ResourceManager.GetString("IzabraniDoktorPacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi doktora kom želite da pošaljete zahtev:.
        /// </summary>
        internal static string izberiDoktora {
            get {
                return ResourceManager.GetString("izberiDoktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Izmeni lek.
        /// </summary>
        internal static string IzmeniLek {
            get {
                return ResourceManager.GetString("IzmeniLek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni opremu.
        /// </summary>
        internal static string IzmeniOpremu {
            get {
                return ResourceManager.GetString("IzmeniOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni prostoriju.
        /// </summary>
        internal static string IzmeniProstoriju {
            get {
                return ResourceManager.GetString("IzmeniProstoriju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj anketa.
        /// </summary>
        internal static string IzvestajAnketa {
            get {
                return ResourceManager.GetString("IzvestajAnketa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Izveštaj anketa u periodu .
        /// </summary>
        internal static string IzvestajAnketaUP {
            get {
                return ResourceManager.GetString("IzvestajAnketaUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jačina leka [mg]:.
        /// </summary>
        internal static string JacinaLeka {
            get {
                return ResourceManager.GetString("JacinaLeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        internal static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina:.
        /// </summary>
        internal static string Kolicina {
            get {
                return ResourceManager.GetString("Kolicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to količina.
        /// </summary>
        internal static string kolicinaM {
            get {
                return ResourceManager.GetString("kolicinaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina za prebacivanje:.
        /// </summary>
        internal static string KolicinaZaPrebacivanje {
            get {
                return ResourceManager.GetString("KolicinaZaPrebacivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar pacijenta:.
        /// </summary>
        internal static string KomentarPacijenta {
            get {
                return ResourceManager.GetString("KomentarPacijenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lek.
        /// </summary>
        internal static string lekM {
            get {
                return ResourceManager.GetString("lekM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekovi.
        /// </summary>
        internal static string Lekovi {
            get {
                return ResourceManager.GetString("Lekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lek za dodavanje.
        /// </summary>
        internal static string LekZaDodavanje {
            get {
                return ResourceManager.GetString("LekZaDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lek za izmenu.
        /// </summary>
        internal static string LekZaIzmenu {
            get {
                return ResourceManager.GetString("LekZaIzmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za sastanke.
        /// </summary>
        internal static string meetingRoom {
            get {
                return ResourceManager.GetString("meetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spajanje.
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način upotrebe:.
        /// </summary>
        internal static string NacinUpotrebe {
            get {
                return ResourceManager.GetString("NacinUpotrebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi izveštaj.
        /// </summary>
        internal static string NapraviIzvestaj {
            get {
                return ResourceManager.GetString("NapraviIzvestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        internal static string Nazad {
            get {
                return ResourceManager.GetString("Nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv leka:.
        /// </summary>
        internal static string NazivLeka {
            get {
                return ResourceManager.GetString("NazivLeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naziv.
        /// </summary>
        internal static string nazivM {
            get {
                return ResourceManager.GetString("nazivM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv opreme:.
        /// </summary>
        internal static string NazivOpreme {
            get {
                return ResourceManager.GetString("NazivOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifikacije.
        /// </summary>
        internal static string Notifikacije {
            get {
                return ResourceManager.GetString("Notifikacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Obriši lek.
        /// </summary>
        internal static string ObrisiLek {
            get {
                return ResourceManager.GetString("ObrisiLek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši opremu.
        /// </summary>
        internal static string ObrisiOpremu {
            get {
                return ResourceManager.GetString("ObrisiOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši prostoriju.
        /// </summary>
        internal static string ObrisiProstoriju {
            get {
                return ResourceManager.GetString("ObrisiProstoriju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši sastojak.
        /// </summary>
        internal static string ObrisiSastojak {
            get {
                return ResourceManager.GetString("ObrisiSastojak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena opreme bolnice:.
        /// </summary>
        internal static string OcenaOpreme {
            get {
                return ResourceManager.GetString("OcenaOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena za doktora.
        /// </summary>
        internal static string OcenaZaDoktora {
            get {
                return ResourceManager.GetString("OcenaZaDoktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to od:.
        /// </summary>
        internal static string od {
            get {
                return ResourceManager.GetString("od", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbijeni lekovi.
        /// </summary>
        internal static string OdbijeniLekovi {
            get {
                return ResourceManager.GetString("OdbijeniLekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        internal static string OdjaviSe {
            get {
                return ResourceManager.GetString("OdjaviSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za operaciju.
        /// </summary>
        internal static string operatingRoom {
            get {
                return ResourceManager.GetString("operatingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema.
        /// </summary>
        internal static string Oprema {
            get {
                return ResourceManager.GetString("Oprema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema za dodavanje.
        /// </summary>
        internal static string OpremaZaDodavanje {
            get {
                return ResourceManager.GetString("OpremaZaDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema za izmenu.
        /// </summary>
        internal static string OpremaZaIzmenu {
            get {
                return ResourceManager.GetString("OpremaZaIzmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        internal static string Otkazi {
            get {
                return ResourceManager.GetString("Otkazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per os.
        /// </summary>
        internal static string per_os {
            get {
                return ResourceManager.GetString("per os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        internal static string Podesavanja {
            get {
                return ResourceManager.GetString("Podesavanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogedaj anketu.
        /// </summary>
        internal static string PogledajAnketu {
            get {
                return ResourceManager.GetString("PogledajAnketu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoć.
        /// </summary>
        internal static string Pomoc {
            get {
                return ResourceManager.GetString("Pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program se sastoji iz 8 glavnih stranica: 
        ///
        ///1. Notifikacije - Notifikacije za ulogovanog korisnika
        ///2. Prostorije - Pregled prostorija u bolnici
        ///3. Lekovi - Pregled lekov u bolnici
        ///4. Oprema - Pregled opreme u bolnici
        ///5. Ankete - Pregled anketa koje su popunili pacijenti
        ///6. Podešavanja - Podešavanja koja ukljucuju promenu teme i jezika aplikacije
        ///7. Profil - Informacije o ulogovanom korisniku
        ///8. Pomoć - pomoć za korisnika
        ///
        ///Komande:
        ///
        ///Komanda Dodaj- dodavanje novog entiteta u program
        ///Komanda Izme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PomocText {
            get {
                return ResourceManager.GetString("PomocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi.
        /// </summary>
        internal static string Ponisti {
            get {
                return ResourceManager.GetString("Ponisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi dodavanje.
        /// </summary>
        internal static string PonistiDodavanje {
            get {
                return ResourceManager.GetString("PonistiDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi izmenu.
        /// </summary>
        internal static string PonistiIzmenu {
            get {
                return ResourceManager.GetString("PonistiIzmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošalji doktoru.
        /// </summary>
        internal static string PosaljiDoktoru {
            get {
                return ResourceManager.GetString("PosaljiDoktoru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi dodavanje.
        /// </summary>
        internal static string PotvrdiDodavanje {
            get {
                return ResourceManager.GetString("PotvrdiDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi izmenu.
        /// </summary>
        internal static string PotvrdiIzmenu {
            get {
                return ResourceManager.GetString("PotvrdiIzmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled opreme.
        /// </summary>
        internal static string PregledOpreme {
            get {
                return ResourceManager.GetString("PregledOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premesti opremu.
        /// </summary>
        internal static string PremestiOpremu {
            get {
                return ResourceManager.GetString("PremestiOpremu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga:.
        /// </summary>
        internal static string Pretraga {
            get {
                return ResourceManager.GetString("Pretraga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prezime.
        /// </summary>
        internal static string prezimeM {
            get {
                return ResourceManager.GetString("prezimeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorija za dodavanje.
        /// </summary>
        internal static string ProstorijaZaDodavanje {
            get {
                return ResourceManager.GetString("ProstorijaZaDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorija za izmenu.
        /// </summary>
        internal static string ProstorijaZaIzmenu {
            get {
                return ResourceManager.GetString("ProstorijaZaIzmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorije.
        /// </summary>
        internal static string Prostorije {
            get {
                return ResourceManager.GetString("Prostorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspored po prostorijama.
        /// </summary>
        internal static string RaporedPoPro {
            get {
                return ResourceManager.GetString("RaporedPoPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlog renoviranja:.
        /// </summary>
        internal static string RazlogRenoviranja {
            get {
                return ResourceManager.GetString("RazlogRenoviranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za odmor.
        /// </summary>
        internal static string recoveryRoom {
            get {
                return ResourceManager.GetString("recoveryRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rektalno.
        /// </summary>
        internal static string rektalno {
            get {
                return ResourceManager.GetString("rektalno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviranje prostorije u periodu.
        /// </summary>
        internal static string RenoviranjeProstorijeUP {
            get {
                return ResourceManager.GetString("RenoviranjeProstorijeUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sadržaj.
        /// </summary>
        internal static string sadrzaj {
            get {
                return ResourceManager.GetString("sadrzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sastojci.
        /// </summary>
        internal static string Sastojci {
            get {
                return ResourceManager.GetString("Sastojci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specijalizacija.
        /// </summary>
        internal static string specijalizacijaM {
            get {
                return ResourceManager.GetString("specijalizacijaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razdvajanje.
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprat.
        /// </summary>
        internal static string spratM {
            get {
                return ResourceManager.GetString("spratM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednja ocena bolnice:.
        /// </summary>
        internal static string SrecnjaOcenaBolnice {
            get {
                return ResourceManager.GetString("SrecnjaOcenaBolnice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednja ocena doktora:.
        /// </summary>
        internal static string SrednjaOcenaDoktora {
            get {
                return ResourceManager.GetString("SrednjaOcenaDoktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        internal static string Srpski {
            get {
                return ResourceManager.GetString("Srpski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statička.
        /// </summary>
        internal static string staticka {
            get {
                return ResourceManager.GetString("staticka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sublingavlno.
        /// </summary>
        internal static string sublingvalno {
            get {
                return ResourceManager.GetString("sublingvalno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sva oprema.
        /// </summary>
        internal static string sva {
            get {
                return ResourceManager.GetString("sva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        internal static string Svetla {
            get {
                return ResourceManager.GetString("Svetla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string Tamna {
            get {
                return ResourceManager.GetString("Tamna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon: 0650702039.
        /// </summary>
        internal static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema:.
        /// </summary>
        internal static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip leka:.
        /// </summary>
        internal static string TipLeka {
            get {
                return ResourceManager.GetString("TipLeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip.
        /// </summary>
        internal static string tipM {
            get {
                return ResourceManager.GetString("tipM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip opreme:.
        /// </summary>
        internal static string TipOpreme {
            get {
                return ResourceManager.GetString("TipOpreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip prostorije:.
        /// </summary>
        internal static string TipProstorije {
            get {
                return ResourceManager.GetString("TipProstorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip renoviranja:.
        /// </summary>
        internal static string TipRenoviranja {
            get {
                return ResourceManager.GetString("TipRenoviranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U magacin.
        /// </summary>
        internal static string UMagacin {
            get {
                return ResourceManager.GetString("UMagacin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite novi sastojak leka:.
        /// </summary>
        internal static string UnesiteNoviSastojakLeka {
            get {
                return ResourceManager.GetString("UnesiteNoviSastojakLeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U prostoriju.
        /// </summary>
        internal static string UProstoriju {
            get {
                return ResourceManager.GetString("UProstoriju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime: tatamata.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to način upotrebe.
        /// </summary>
        internal static string useTypeM {
            get {
                return ResourceManager.GetString("useTypeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme prebacivanja:.
        /// </summary>
        internal static string VremePrebacivanja {
            get {
                return ResourceManager.GetString("VremePrebacivanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži renoviranje.
        /// </summary>
        internal static string ZakaziRenoviranje {
            get {
                return ResourceManager.GetString("ZakaziRenoviranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamenski lekovi:.
        /// </summary>
        internal static string ZamenskiLekovi {
            get {
                return ResourceManager.GetString("ZamenskiLekovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanimanje: Upravnik.
        /// </summary>
        internal static string zanimanje {
            get {
                return ResourceManager.GetString("zanimanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi.
        /// </summary>
        internal static string Zavrsi {
            get {
                return ResourceManager.GetString("Zavrsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi dodavanje.
        /// </summary>
        internal static string ZavrsiDodavanje {
            get {
                return ResourceManager.GetString("ZavrsiDodavanje", resourceCulture);
            }
        }
    }
}
